<%@ control language="C#" autoeventwireup="true" inherits="widgets_Newsletter_edit, App_Web_qlkt5kax" %>
<asp:GridView 
  runat="server"
  id="gridEmails"
  AlternatingRowStyle-BackColor="#F1F1F1"
  AutoGenerateColumns="False"
  AutoGenerateDeleteButton="true">
 
  <Columns>
    <asp:BoundField HeaderText="Email" DataField="innertext" />
  </Columns> 
</asp:GridView>