//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _PUGBUDDY_CONTROL_NETDUINO_H_
#define _PUGBUDDY_CONTROL_NETDUINO_H_

#include <TinyCLR_Interop.h>
struct Library_PugBuddy_Control_Netduino_ElectricSpeedController_API_SpeedController
{
    static const int FIELD__esc = 1;
    static const int FIELD__range = 2;
    static const int FIELD__inverted = 3;
    static const int FIELD__escModel = 4;
    static const int FIELD__DriveMode = 5;
    static const int FIELD__currentThrottle = 6;


    //--//

};

struct Library_PugBuddy_Control_Netduino_ElectricSpeedController_API_ESC_AutoSequencer
{
    static const int FIELD__esc = 1;


    //--//

};

struct Library_PugBuddy_Control_Netduino_PPM_Decoder_API_PPM_Channel
{
    static const int FIELD__inputHandle = 1;
    static const int FIELD__inputRange = 2;
    static const int FIELD__outputRange = 3;
    static const int FIELD__internalRead = 4;
    static const int FIELD__ticks = 5;


    //--//

};

struct Library_PugBuddy_Control_Netduino_PugBuddy_Control_Netduino_Listener
{
    static const int FIELD__portNumber = 1;
    static const int FIELD__listeningSocket = 2;
    static const int FIELD__requestReceived = 3;


    //--//

};

struct Library_PugBuddy_Control_Netduino_PugBuddy_Control_Netduino_Program
{
    static const int FIELD_STATIC__steering = 0;
    static const int FIELD_STATIC__xl5 = 1;


    //--//

};

struct Library_PugBuddy_Control_Netduino_PugBuddy_Control_Netduino_Request
{
    static const int FIELD__method = 1;
    static const int FIELD__url = 2;
    static const int FIELD__client = 3;


    //--//

};

struct Library_PugBuddy_Control_Netduino_Servo_API_Servo
{
    static const int FIELD__servo = 1;
    static const int FIELD__range = 2;
    static const int FIELD__inverted = 3;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_PugBuddy_Control_Netduino;

#endif  //_PUGBUDDY_CONTROL_NETDUINO_H_
